messages:
  plugin-enabled: "CustomJoinMessages a Ã©tÃ© activÃ© !"
  plugin-disabled: "CustomJoinMessages a Ã©tÃ© dÃ©sactivÃ© !"

  no-permission: "&c n'avez pas la permission d'exÃ©cuter cette commande."
  no-found-message: "&cMessage introuvable !"

  only-players: "&cSeuls les joueurs peuvent exÃ©cuter cette commande."



join-messages:
  tag1:
    display-name: "&aBienvenue!"
    lore:
      - "&7Ce message s'affiche"
      - "&7quand un joueur rejoint."
    permission: "customjoinmessages.tag1"
    join-message: "&a[PLAYER] a rejoint le serveur ! ğŸ‰"

  tag2:
    display-name: "&bHello!"
    lore:
      - "&7Un autre message"
      - "&7personnalisÃ©."
    permission: "customjoinmessages.tag2"
    join-message: "&b[PLAYER] est lÃ  ! ğŸ‘‹"

